Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -77,6 +77,14 @@ jobs:
           echo "$STATUS" > report/sonar-gate.json
           SONAR_STATUS=$(echo "$STATUS" | jq -r '.projectStatus.status')
           echo "SonarQube Quality Gate Status: $SONAR_STATUS"
+
+          if [ "$SONAR_STATUS" != "OK" ]; then
+            echo "Quality Gate failed. Failing the pipeline."
+            EXIT_CODE=1
+          else
+            EXIT_CODE=0
+          fi
+            echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV
  
       - name: Push Sonar Report to trivy Branch
         run: |
@@ -98,6 +106,10 @@ jobs:
           git remote set-url origin https://ulchatur:${{ secrets.PAT_TOKEN }}@github.com/ulchatur/java_address.git
           git pull origin trivy --rebase
           git push origin trivy
+
+      - name: Fail Pipeline if Quality Gate Failed
+        if: env.EXIT_CODE == '1'
+        run: exit 1
 
   docker-build:
     runs-on: ubuntu-latest
