Update sonar.yml

diff --git a/.github/workflows/sonar.yml b/.github/workflows/sonar.yml
--- a/.github/workflows/sonar.yml
+++ b/.github/workflows/sonar.yml
@@ -12,6 +12,8 @@ jobs:
         run: |
           aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
           aws ec2 wait instance-running --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
+          echo "Waiting for 30 seconds to ensure ec2 is up"
+          sleep 45
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -44,18 +46,18 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
- #     - name: Check SonarQube Quality Gate
-  #      run: |
-   #       SONAR_URL="${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=my-Java-web-app"
-    #      STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "$SONAR_URL" | jq -r '.projectStatus.status')
-     #     echo "SonarQube Quality Gate Status: $STATUS"
-      #    if [ "$STATUS" != "OK" ]; then
-       #     echo "Quality Gate failed. Failing the pipeline."
-        #    exit 1
-         # fi
-        #env:
-         # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          #SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+      - name: Check SonarQube Quality Gate
+        run: |
+          SONAR_URL="${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=my-Java-web-app"
+          STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "$SONAR_URL" | jq -r '.projectStatus.status')
+          echo "SonarQube Quality Gate Status: $STATUS"
+          if [ "$STATUS" != "OK" ]; then
+            echo "Quality Gate failed. Failing the pipeline."
+            exit 1
+          fi
+        env:
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
 
   docker-build:
     runs-on: ubuntu-latest
